baseURL: https://kostis-portfolio.netlify.app/ 
languageCode: en-us
title:  Portofolio Website from Kaize Ying for Kostis
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Brought up in China, I have studied across China, Singapore, and the UK. I am now a MFA student at LBS. 
      
      Prior, I studied engineering during my undergraduate and graduated earlier this year.
    title: Hi, my name is Kaize Ying, LBS MFA 2022, thanks for visiting my website!
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Park Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: kying.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: + 44 7983-472801
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
        #label: Twitter
        #url: https://www.twitter.com
      #- icon: fa-facebook
        #label: Facebook
        #url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/fy0803/
      - icon: fa-github
        label: GitHub
        url: https://github.com/KaizeYing
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/feed/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - #name: Blogs
        url: blogs
      #- name: Generic Blog
       # url: blogs/ipsum
      #- name: Elements
       # url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: Kaize.jpg
        subtitle: Wanna know more about me?
        title: Self-intro
        url: blogs/kaize_intro
      - image: Oxford.jpg
        subtitle: My Alma mater
        title: Oxford
        url: https://www.ox.ac.uk/
      - image: Bike.jpg
        subtitle: Excess rentals in TfL bike sharing
        title: Bike
        url: blogs/bike_analysis
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: 
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "
    Besides my academic interets in novel materials and professional interests in investing, I have spent a large amount of time exploring different things.
      \n  For example, I enjoy cooking, travelling, moutain-climbing, and used to take a train trip back from London to my hometown in China.
      \n  Feel free to reach out if we have something in common so that we can have a chat :)      "
    title: My
    url: blogs
